--DB: ammdb; user: ammdb; pass: ammdb ;

CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);

CREATE TABLE utenti (
    utente_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    cognome varchar(256),
    password VARCHAR(256) NOT NULL,
    frase varchar (1024)
    urlFotoProfilo VARCHAR(256)
);

CREATE TABLE posts 
(
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(postType_id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(utente_id)
);

CREATE TABLE segui 
(
   follower INTEGER,
   FOREIGN KEY (follower) REFERENCES utente(utenti_id),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES utente(utenti_id),
   PRIMARY KEY (follower, followed)
);
CREATE TABLE gruppi
(
    gruppo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(256),
    postGruppo INTEGER,
    FOREIGN KEY (postGruppo) REFERENCES posts(post_id)
);
CREATE TABLE membriGruppi
(
    gruppo INTEGER,
    FOREIGN KEY (gruppo) REFERENCES gruppi(gruppo_id),
    membro INTEGER,
    FOREIGN KEY (membro) REFERENCES utenti(utente_id),
    PRIMARY KEY (gruppo,membro)
);

--Popolamento tabella utenti
INSERT INTO utenti (utente_id, nome, cognome, password, urlfotoprofilo)
VALUES (default,
        'Marco',
        'Pittau',
        '123',
        'img/icon2.jpg');

INSERT INTO utenti (utente_id, nome, cognome, password, urlfotoprofilo)
VALUES (default,
        'Tommaso',
        'ppppp',
        '123',
        'img/icon1.jpg');

--Popolamento tabella PostType
INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'TEXT');

--Popolamento tabella Post
INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'hey tu, dico a te',
        1,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'https://68.media.tumblr.com/51942e1f788f7209ee0f6db7cfc5e0fb/tumblr_n37ycpbMZf1rkxod7o1_500.jpg',
        1,
        1);
